import PricingIndex from "@/app/components/theme-pages/pricing";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Pricing Page",
  description: "Generated by create next app",
};
const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Pricing",
  },
];

const Pricing = () => {
  return (
    <>
      <BreadcrumbComp title="Pricing" items={BCrumb} />
      <PricingIndex />
    </>
  );
};

export default Pricing;
