import React from "react";
import type { Metadata } from "next";
import LoginPageClient from "./LoginPageClient";

export const metadata: Metadata = {
  title: "Side Login Authentication",
  description: "Generated by create next app",
};

const Login = () => {
  return <LoginPageClient />;
};

export default Login;
